spring:
  application:
    name: interbank-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info

account:
  service:
    url: http://localhost:8081

transaction:
  service:
    url: http://localhost:8082
